version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: crud-app
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: crud-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
